language: node_js
os: linux
dist: bionic
node_js:
  12
before_script:
  - npm install -g gulp@4.0.2
env:
  global:
    secure: "LMTws612lFT730D8cyoE8L15hdFdj1Nx2RQFZynw0xk4Iel1AFFGhlPRYAsx5NV9NorR3raUSPp0hMNau2OXjoYjk2julK2RAbjGCJKlk8GEe4iEyYr10ZYXhsgIMtBUM8lbEXIHWfF1IDfTiPTai1GyNjwrmzt+JgzMhfshE31/bTIsyZpolr1966328h795keH3nDG3CoHrbmKEkSQbu5vaOMIGIMdvWGCAsm7/aZQaw+zcewH/JxnyW2/8pK3e0v/xB2AMbwXLropHE9MLu8s8zOXhwGwE2evm1EGKvdrFeEIeW7liyCVWrUe48LfR7KkLgb2R4gpOU6vrQF+P0wey2nZRa1EUoV6LpYPfLWt5aFrhKt3V2QMN3FT1x6u+sUFgnRQJVznGF1HkLyXUllOkGZhwIO4xIJZ6oQGt2Gp2puJK7ehuBEr/jkpGc+4VVNUL1wnabVPYphFdgng3seTdp/GUQjtuihRFACWmfw6kXv7NgeVkLqK6iMSYGR8A2Z9YSOOKGys9lakj/fhgVcJBU+Oohi7JvBqFADTL3hnbcDZZ9k45V3NtL9+Iivp87L9lpIYILKoBBlpHsurSLTiO0eJH4Zy0aVprOzVvJPGkkQ6kmyZv48kaypg3DiUxc8hqGCXMctmA7SO6+y6NWGSjyyNMDlhueRQG1M8kVw="

script: gulp build
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  strategy: git
  local_dir: dist
  on:
    branch: master
  edge: true
